Chapter-14/my_app/catalog/models.py
from my_app import db

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    price = db.Column(db.Float)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship(
        'Category', backref=db.backref('products', lazy='dynamic')
    )

    def __init__(self, name, price, category):
        self.name = name
        self.price = price
        self.category = category

    def __repr__(self):
        return '<Product %d>' % self.id


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Category %d>' % self.id

Chapter-14/my_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
app.config['OPENAI_KEY'] = 'Your own API Key'
db = SQLAlchemy(app)

app.secret_key = 'some_random_key'

from my_app.catalog.views import catalog
app.register_blueprint(catalog)

with app.app_context():
    db.create_all()

Chapter-14/my_app/catalog/views.py
import openai
from functools import wraps
from flask import request, Blueprint, render_template, jsonify, flash, \
    redirect, url_for
from my_app import db, app
from my_app.catalog.models import Product, Category
from sqlalchemy.orm import join

catalog = Blueprint('catalog', __name__)


def template_or_json(template=None):
    """"Return a dict from your view and this will either
    pass it to a template or render json. Use like:

    @template_or_json('template.html')
    """
    def decorated(f):
        @wraps(f)
        def decorated_fn(*args, **kwargs):
            ctx = f(*args, **kwargs)
            if request.headers.get("X-Requested-With") == "XMLHttpRequest" or not template:
                return jsonify(ctx)
            else:
                return render_template(template, **ctx)
        return decorated_fn
    return decorated


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@catalog.route('/')
@catalog.route('/home')
@template_or_json('home.html')
def home():
    products = Product.query.all()
    return {'count': len(products)}


@catalog.route('/product/<id>')
def product(id):
    product = Product.query.get_or_404(id)
    return render_template('product.html', product=product)


@catalog.route('/products')
@catalog.route('/products/<int:page>')
def products(page=1):
    products = Product.query.paginate(page=page, per_page=10)
    return render_template('products.html', products=products)


@catalog.route('/product-create', methods=['GET', 'POST'])
def create_product():
    if request.method == 'POST':
        name = request.form.get('name')
        price = request.form.get('price')
        categ_name = request.form.get('category')
        category = Category.query.filter_by(name=categ_name).first()
        if not category:
            category = Category(categ_name)
        product = Product(name, price, category)
        db.session.add(product)
        db.session.commit()
        flash('The product %s has been created' % name, 'success')
        return redirect(url_for('catalog.product', id=product.id))
    return render_template('product-create.html')


@catalog.route('/product-search')
@catalog.route('/product-search/<int:page>')
def product_search(page=1):
    name = request.args.get('name')
    price = request.args.get('price')
    company = request.args.get('company')
    category = request.args.get('category')
    products = Product.query
    if name:
        products = products.filter(Product.name.like('%' + name + '%'))
    if price:
        products = products.filter(Product.price == price)
    if company:
        products = products.filter(Product.company.like('%' + company + '%'))
    if category:
        products = products.select_from(join(Product, Category)).filter(
            Category.name.like('%' + category + '%')
        )
    return render_template(
        'products.html', products=products.paginate(page=page, per_page=10)
    )


@catalog.route('/product-search-gpt', methods=['GET', 'POST'])
def product_search_gpt():
    if request.method == 'POST':
        query = request.form.get('query')

        openai.api_key = app.config['OPENAI_KEY']

        prompt = """Context: Ecommerce electronics website\n
            Operation: Create search queries for a product\n
            Product: """ + query

        response = openai.Completion.create(
            model="text-davinci-003",
            prompt=prompt,
            temperature=0.2,
            max_tokens=60,
            top_p=1.0,
            frequency_penalty=0.5,
            presence_penalty=0.0
        )

        return response['choices'][0][
            'text'].strip('\n').split('\n')[1:]
    return render_template('product-search-gpt-demo.html')


@catalog.route('/chat-gpt', methods=['GET', 'POST'])
def chat_gpt():
    if request.method == 'POST':
        msg = request.form.get('msg')

        openai.api_key = app.config['OPENAI_KEY']

        messages = [
            {
                "role": "system",
                "content": "You are a helpful chat assistant for a generic electronics Ecommerce website"
            },
            {"role": "user", "content": msg}
        ]

        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages
        )

        return jsonify(
            message=response['choices'][0]['message']['content']
        )
    return render_template('chatgpt-demo.html')


@catalog.route('/category-create', methods=['POST',])
def create_category():
    name = request.form.get('name')
    category = Category(name)
    db.session.add(category)
    db.session.commit()
    return render_template('category.html', category=category)


@catalog.route('/category/<id>')
def category(id):
    category = Category.query.get_or_404(id)
    return render_template('category.html', category=category)


@catalog.route('/categories')
def categories():
    categories = Category.query.all()
    return render_template('categories.html', categories=categories)

Chapter-14/my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Framework Cookbook</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/awesomplete/1.1.5/awesomplete.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('catalog.home') }}">Flask Cookbook</a>
        </div>
      </div>
    </div>
    <div class="container">
    <br/>
    <div>
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
      </div>
    {% block container %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/awesomplete/1.1.5/awesomplete.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

Chapter-14/my_app/templates/chatgpt-demo.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <ul class="list-group" id="chat-list">
      <li class="list-group-item">
        <span class="badge">GPT</span>
        How can I help you?
      </li>
    </ul>
    <div class="input-group">
      <input type="text" class="form-control" name="message" placeholder="Enter your message" aria-describedby="chat-input">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button" data-loading-text="Loading..." id="send-message">Send</button>
      </span>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script>

function appendToChatList(mode, message) {
  $( "#chat-list" ).append( '<li class="list-group-item"><span class="badge">' + mode + '</span>' + message + '</li>' );
}
$(document).ready(function(){
  $('button#send-message').click(function() {
    var send_btn = $(this).button('loading');
    const inputChat = document.querySelector( 'input[name="message"]' );
    var message = inputChat.value;

    appendToChatList('Human', message);

    inputChat.value = '';

    $.ajax({
      url: '{{ url_for("catalog.chat_gpt") }}',
      type: 'POST',
      dataType: "json",
      data: {
          msg: message
      }
    })
    .done(function(data) {
      appendToChatList('GPT', data.message);
      send_btn.button('reset');
    });

  });
});
</script>
{% endblock %}

Chapter-14/my_app/templates/product-create.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <form
        class="form-horizontal"
        method="POST"
        action="{{ url_for('catalog.create_product') }}"
        role="form">
      <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="name" name="name">
        </div>
      </div>
      <div class="form-group">
        <label for="price" class="col-sm-2 control-label">Price</label>
        <div class="col-sm-10">
          <input type="number" class="form-control" id="price" name="price">
        </div>
      </div>
      <div class="form-group">
        <label for="category" class="col-sm-2 control-label">Category</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="category" name="category">
        </div>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
{% endblock %}

Chapter-14/my_app/templates/product-search-gpt-demo.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <form
        class="form-horizontal"
        role="form">
      <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Query</label>
        <div class="col-sm-10">
          <input type="text" class="form-control awesomplete" id="query" name="query">
        </div>
      </div>
    </form>
  </div>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function(){

  const input = document.querySelector( 'input[name="query"]' );

  const awesomplete = new Awesomplete( input, { tabSelect: true, minChars: 5 } );
  
  function ajaxResults() {
    $.ajax({
        url: '{{ url_for("catalog.product_search_gpt") }}',
        type: 'POST',
        dataType: "json",
        data: {
            query: input.value
        }
    })
    .done(function(data) {
        awesomplete.list = data;
    });
  };

  input.addEventListener( 'keyup', ajaxResults );
});
</script>
{% endblock %}

Chapter-14/my_app/templates/product.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <h1>{{ product.name }}<small> {{ product.category.name }}</small></h1>
    <h4>{{ product.company }}</h4>
    <h3>{{ product.price }}</h3>
  </div>
{% endblock %}

Chapter-14/my_app/templates/products.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    {% for product in products.items %}
      <div class="well">
        <h2>
          <a href="{{ url_for('catalog.product', id=product.id) }}">{{ product.name }}</a>
          <small>$ {{ product.price }}</small>
        </h2>
      </div>
    {% endfor %}
    {% if products.has_prev %}
      <a href="{{ url_for(request.endpoint, page=products.prev_num) }}">
        {{"<< Previous Page"}}
      </a>
    {% else %}
      {{"<< Previous Page"}}
    {% endif %} |
    {% if products.has_next %}
      <a href="{{ url_for(request.endpoint, page=products.next_num) }}">
        {{"Next page >>"}}
      </a>
    {% else %}
      {{"Next page >>"}}
    {% endif %}
  </div>
{% endblock %}